services:
  - type: web
    name: bus-booking-backend
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        value: mongodb+srv://agrawalmuskan5885_db_user:5Or8O3UfalJDS7nL@cluster0.jhtu7if.mongodb.net/bus_booking?retryWrites=true&w=majority
      - key: FRONTEND_URL
        value: https://recent-indol.vercel.app
    healthCheckPath: /health
    autoDeploy: true